---
- name: Deploy Kubernetes resources using manifest file
  hosts: kubeserver
  become: true
  tasks:
    - name: Check if Deployment exists
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        namespace: default
        name: k8s-pod
      register: existing_deployment
      ignore_errors: yes

    - name: Delete Deployment if exists
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: k8s-pod
            namespace: default
      when: existing_deployment is defined and existing_deployment is not none

    - name: Check if Service exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Service
        namespace: default
        name: k8s-svc
      register: existing_service
      ignore_errors: yes

    - name: Delete Service if exists
      kubernetes.core.k8s:
        state: absent
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: k8s-svc
            namespace: default
      when: existing_deployment is defined and existing_deployment is not none

    - name: Apply manifest file using kubectl
      shell: kubectl apply -f /etc/kubernetes/kubernetes_deploy.yml
