---
- hosts: localhost  # Assuming you're running Ansible locally
  connection: local
  become: true
  vars:
    build_number: "{{ lookup('env', 'BUILD_NUMBER') }}"
     
  tasks:   
    - name: Docker build
      shell:
        cmd: |
          cd {{ workspace }}
          docker build --file Dockerfile --tag sarvanipamarti/abc_technologies:{{ build_number }} .
      vars:
        workspace: "{{ lookup('env', 'WORKSPACE') }}"

    - name: Push Docker image
      shell:
        cmd: |
          docker push docker.io/sarvanipamarti/abc_technologies:{{ build_number }}

